### ISSUE TITLE
CUFFT_INTERNAL_ERROR on RTX4090

### ISSUE THREAD

**Issue by dividebysandwich** [domesticatedviking/TextyMcSpeechy#49]
I'm running arch on a 4090 and try as I might, I get `RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR`
nvidia drivers and container toolkit are installed, I have tried using the premade image as well as rolling my own, and I have tried using cuda 12.1.0 in the Dockerfile instead of 11.8.0
I have tried training from scratch as well as using the pretrained checkpoints, I lowered the batch size, and also tried running the training with no desktop running so as to have the max amount of GPU RAM available.

I also tried various versions of cuda and cudnn on the host system, no joy. If I run python outside docker I can run cufft test commands with no issue. I also ran print(torch.cuda.get_device_name(0)) inside the container and it returns the correct graphics card name.

However, running `torch.fft.rfft(torch.randn(1000).cuda())` inside the container gives me that dreaded cuFFT error again, while it does work on the host system outside the container. Any ideas?

**Comment by dividebysandwich** [comment]
Update: I believe I got it working by changing the following versions in the Dockerfile and running docker compose --build:

On top, change the FROM line to this:

`FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04 AS base`

In the pip install lines, change the versions for torch as follows:

`torch==2.4.1 pytorch-lightning==1.9.0 torchmetrics==0.11.4`

Of course the container has to be started with local_container_run.sh
